/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.jpanel;

import DAO.Personas;
import JPA.PersonasJpaController;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
//import javax.persistence.EntityManager;
//import javax.persistence.EntityManagerFactory;
//import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gonza
 */
public final class jp_listado_personas extends javax.swing.JPanel { //implemnta patron observador

    private DefaultTableModel modelo;

    /**
     * Creates new form jp_listado_personas
     */
    public jp_listado_personas() {
        initComponents();
        crear_modelo();
        //cargar_personas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_personas = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("LISTADO DE PERSONAS"));

        tbl_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_personas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void crear_modelo() {
        modelo = null;
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{"ID", "NOMBRE",
                        "APELLIDO", "TIPO"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, true, true, true
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tbl_personas.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
        }
    }

    void cargar_personas() {

        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("inmo_mvn_PU");
            EntityManager em = emf.createEntityManager();

            PersonasJpaController personas_jpa = new PersonasJpaController(emf);

            em.getTransaction().begin();
            Object o[] = null;
            List<Personas> lista = personas_jpa.findPersonasEntities();
            for (int i = 0; i < lista.size(); i++) {
                modelo.addRow(o);
                modelo.setValueAt(lista.get(i).getId(), i, 0);
                modelo.setValueAt(lista.get(i).getNombre(), i, 1);
                modelo.setValueAt(lista.get(i).getApellido(), i, 2);
                //modelo.setValueAt(lista.get(i).get, i, 0);VER LO DE TIPO_PERSONA
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_personas;
    // End of variables declaration//GEN-END:variables
}
